name: Build Environment
run-name: ${{ github.actor }} building environment
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses actions/checkout@v2
      - run: echo "Created File" > test_file
      - name: Cache test file
        uses: actions/cache/save@v3
        with:
          key: test_file
          path: test_file

