name: Keep Cache Alive
on: [respository_dispatch, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
      - name: Cache test file
        uses: actions/cache/restore@v3
        with:
          key: test_file
          path: test_file
      - run: cat test_file

